### ISSUE TITLE
Organize Images

### ISSUE THREAD

**Issue by bhuvy2** [illinois-cs241/illinois-cs241.github.io#103]
Our Images folder is a mess. We should have some naming scheme or convention.

**Comment by PradyumnaShome** [comment]
Refactored assignment images, and everything in the images folder, via 06b28b25a2bbd8b118157a299810e31fd1952e66

Updated and verified all links via these two commits on the assignment-docs repository:

- https://github.com/illinois-cs241/assignment-docs/commit/862efbdc59e958b92718cb1583a0709a56e47f14
- https://github.com/illinois-cs241/assignment-docs/commit/67a0dd33691d02b55bbe98ed2cb22dead20402fd

Is this good enough to close this, @bhuvy2?

**Comment by aneeshdurg** [comment]
Hmm if the images are coupled with assignment-docs maybe they should be moved into the assignment-docs repo? That might be a larger refractor though.

**Comment by bhuvy2** [comment]
Closing in favor of another issue
