### ISSUE TITLE
Modification UI

### ISSUE THREAD

**Issue by bchong95** [illinois-cs241/illinois-cs241.github.io#15]
Maybe add something like this:

![image](https://cloud.githubusercontent.com/assets/4381236/16285084/30fdcd78-3889-11e6-9645-e58209add6b8.png)

**Comment by bchong95** [comment]
This will probably get us the "edit on github" link.
http://stackoverflow.com/questions/13243469/how-can-a-jekyll-page-access-its-filename

**Comment by dpzmick** [comment]
Awesome idea

On Thursday, June 23, 2016, Brandon Chong <notifications@github.com> wrote:

> This will probably get us the "edit on github" link.
>
> http://stackoverflow.com/questions/13243469/how-can-a-jekyll-page-access-its-filename
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/illinois-cs/illinois-cs.github.io/issues/15#issuecomment-228176256>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAgwefF0t1I5sr7wWFzJfy5Y67vBIYUGks5qOu6-gaJpZM4I8Qze>
> .
>


-- 
David Zmick
dpzmick.com
dpzmick@gmail.com

**Comment by bchong95** [comment]
This plugin will get the modification time

https://github.com/gjtorikian/jekyll-last-modified-at

**Comment by bchong95** [comment]
Yeah this will give each assignment documentation 2 things:

1) Easy link for course staff (and students if they decide to make a pull request) to make corrections. 
2) Lets the student's know when the last time docs were modified (so they know whether they are looking at the most up to date docs)

**Comment by bchong95** [comment]
Maybe we can also have a page link to it's change log, but I hope our docs won't need that much of a change log anymore :)

**Comment by earwig** [comment]
At the moment I don't think we can do the "last updated" time without making staff manually update the value whenever they change things. The plugin isn't available on GH Pages and they don't allow custom Ruby code. Linking to GitHub and the changelog is the best we can do until GH/Jekyll adds something.

**Comment by earwig** [comment]
Here are a couple proposals. It's tough to integrate with the existing style without it feeling cluttered.

Links:

<img width="1280" alt="screen shot 2016-08-25 at 3 56 21 pm" src="https://cloud.githubusercontent.com/assets/637235/17985718/a2fd26a0-6adc-11e6-8a90-fa8c3e18d0d4.png">

Icon:

<img width="1280" alt="screen shot 2016-08-25 at 3 53 42 pm" src="https://cloud.githubusercontent.com/assets/637235/17985726/a8db6500-6adc-11e6-8255-aea90d3d6335.png">

**Comment by angrave** [comment]
If its not for student use I suggest you put the links lower down in the 
page (after the end of the table of contents or in the footer) and less 
in-your-face vibrant color (e.g.  gray with only subtle blue).

L.

**Comment by bchong95** [comment]
I like the github button better than the blue link in terms of aesthetics. I would like for this to be student facing, since even a 241 student can fix typos and grammar mistakes :)

**Comment by bchong95** [comment]
@earwig For modification time consider writing a webhook

**Comment by earwig** [comment]
So Webhooks won't really work, unless we set up a bot to trigger on post-receive that commits the new modification date on top. That's a bit of unnecessary work.

My current idea is to pull the date dynamically with JS from GitHub.

**Comment by earwig** [comment]
Working demo in the `github-integration` branch. It looks like this:

<img width="1279" alt="screen shot 2016-08-27 at 5 29 21 pm" src="https://cloud.githubusercontent.com/assets/637235/18030447/d5ccf8a8-6c7b-11e6-96e8-550caf4e7942.png">

Date formatting in JS is a pain without pulling in more dependencies. At the moment, all this requires from docs writers is standardizing the due dates so formats match.

**Comment by bchong95** [comment]
Yeah looks solid to me. Send a PR and we can start working on a code review :)

**Comment by bchong95** [comment]
Aight unless we suddenly want an author line and contribution section I think this issue can be closed.
