### ISSUE TITLE
Update quiz schedule + topics for Spring 2020

### ISSUE THREAD

**Issue by PradyumnaShome** [illinois-cs241/illinois-cs241.github.io#170]
Current schedule is for Fall 2019.

Page to edit: https://github.com/illinois-cs241/illinois-cs241.github.io/blob/develop/_pages/quiz_topics.md

**Comment by angrave** [comment]
(I replied to the email but my comments dod not end up here. Weird. Manually adding)

Course | Exam | Duration | Starting date | Ending date
-- | -- | -- | -- | --
CBTF Optional Training | CBTF Orientation (optional) | 50min | 2020-01-21 | 2020-02-02
CS 241 | Week 2 | 50min | 2020-01-30 | 2020-02-01
CS 241 | Week 4 | 50min | 2020-02-13 | 2020-02-15
CS 241 | Week 6 | 50min | 2020-02-27 | 2020-02-29
CS 241 | Week 8 | 50min | 2020-03-11 | 2020-03-13
CS 241 | Week 11 | 50min | 2020-04-02 | 2020-04-04
CS 241 | Week 13 | 50min | 2020-04-16 | 2020-04-18
CS 241 | Week 15 | 50min | 2020-04-30 | 2020-05-02

**Comment by Xiangmingchen** [comment]
#174
