### ISSUE TITLE
Quick Start Guide for late adds

### ISSUE THREAD

**Issue by bchong95** [illinois-cs241/illinois-cs241.github.io#18]
We should have a page dedicated to late adds, so that they know what to do. Maybe even have the site redirect to that page for the first 2 weeks.

**Comment by bhuvan-venkatesh** [comment]
Where do you want this, in the TOC?

**Comment by bchong95** [comment]
I was thinking it would be it's own page, but I guess in terms of navigation it would probably be in the TopNav.

Or we could just add a section to the home page

**Comment by bhuvan-venkatesh** [comment]
Also, what do you want in this exactly? I currently have

* Email engrit to get you a virtual machine
* Email course staff so you can use our SVN (kurtovic2 or bvenkat2 at this point)
* Start working on HW0/Any assignments
* Go to https://prairielearn.engr.illinois.edu and make sure you have our course listed for quizzes
* Start reading the wikibook and handouts (tbd) to catch up on what you are missing.

Anything else?

**Comment by bchong95** [comment]
* SVN is also Engrit
* They should grab a copy of the assignments from `_shared`
* Any missed assignments are their responsibility
* No deadline extensions
* Link to lecture recording, so they can catch up on the lectures
* Join Piazza and read all the posts by instructors

**Comment by bchong95** [comment]
We can add more as we remember.

**Comment by angrave** [comment]
Missed lab of the first weeks of the course is excused if you are not 
yet enrolled.

... and a link to a "quick links summary" (remember the unofficial page 
the students made in Piazza)

**Comment by bhuvan-venkatesh** [comment]
http://cs241.cs.illinois.edu/late_add.html, Linked http://cs241.cs.illinois.edu/#resources. Not sure if directions are clear, so i'll leave the issue open.

**Comment by bchong95** [comment]
I gave some feedback:

https://github.com/illinois-cs241/illinois-cs241.github.io/commit/518ea5206c90206e2a171aeda162bd2d2b7db6c3
