### ISSUE TITLE
Source Repository Github illinois-cs241/docker-tools

### ISSUE THREAD

**Issue by gardner-dev** [illinois-cs241/illinois-cs241.github.io#221]
Hello, I am using **illinois241/clone** image and would really appreciate you pushing dockerfile of this image. Apparently repository does no longer exist.

**Comment by gardner-dev** [comment]
@rod-lin  @PradyumnaShome @ezhang887  any thoughts on that?

**Comment by rod-lin** [comment]
Hey @gardner-dev, the dockerfiles are in a private repo so you were not able to see it.
But I don't see anything private in that particular image so here's the dockerfile and some other related code:
https://gist.github.com/rod-lin/eec86fd1c8ab6e87bdc52d288a134831

**Comment by ayushr2** [comment]
We might make the repo public soon.
