### ISSUE TITLE
Add submission instructions to the template

### ISSUE THREAD

**Issue by bchong95** [illinois-cs241/illinois-cs241.github.io#28]
Every docs should have grading, submission, and academic integrity. No point in assignment writers manually adding this.

**Comment by bchong95** [comment]
We should also add provides/graded files to the front_matter and inject it into this template.

I don't think there is a programmatic way of doing this unless we have a public listing of every file for every assignment and their read/write privileges.

**Comment by earwig** [comment]
Better standardized assignment descriptions is a nice idea. it might be fun to structure some of it like a man page (could we make that work?).

**Comment by bchong95** [comment]
I think it's totally doable, but maybe not worth the effort. Man pages don't really go with google's material design. They also don't provide much room for typography and sectioning. I also think most people prefer the whitespace inefficiency of all the modern web layouts.

In terms of implementation costs you can just create another layout for docs in ```_layouts```. Man pages are plain text so it should take minimal styling.

**Comment by bchong95** [comment]
I think this is higher prioirity than we thought. Everyone is wondering what files are graded in camelCaser

**Comment by bchong95** [comment]
We should also add the learning objectives here.

**Comment by bchong95** [comment]
The submission instruction have been added in this pull request #38 

Will Create branches for learning objectives and graded files

**Comment by bchong95** [comment]
Graded files is resolved in this pull request #39

**Comment by bchong95** [comment]
Learning objectives is resolved in this pull request #40

**Comment by bchong95** [comment]
Wikibook readings is resolved in this pull request #41
