### ISSUE TITLE
Rescale favicons

### ISSUE THREAD

**Issue by earwig** [illinois-cs241/illinois-cs241.github.io#29]
They look pretty blurry up close.

https://github.com/illinois-cs241/illinois-cs241.github.io/blob/master/images/favicons/android-icon-192x192.png

**Comment by earwig** [comment]
CS 241: Linux Programming

**Comment by bchong95** [comment]
Would you prefer this logo?

![](http://www.officialpsds.com/images/thumbs/Microsoft-Windows-Logo-2-psd87390.png)

It scales very well :)
