### ISSUE TITLE
Filesystems Lab: "recursion/nice"->"nice/recursion"

### ISSUE THREAD

**Issue by bershan2** [illinois-cs241/illinois-cs241.github.io#35]
A minor edit to clarify confusion

The "Testing" section has an incorrect example (example 2)
```
$ ./minixfs test.fs ls /directory
recursion
nice
$
```
Should be 
```
$ ./minixfs test.fs ls /directory
nice
recursion
$
```
See https://piazza.com/class/is23se0b8a455k?cid=1663

**Comment by bhuvan-venkatesh** [comment]
Fixed with d4d5e18
