### ISSUE TITLE
SEO Optimizations

### ISSUE THREAD

**Issue by bchong95** [illinois-cs241/illinois-cs241.github.io#37]
![image](https://cloud.githubusercontent.com/assets/4381236/20243105/27ae716e-a90e-11e6-86b6-dbc586c7e0f9.png)

1) We are not the first result
2) The title is syllabus instead of something like "CS 241: Systems Programming"
3) The little text blub is about our cheating policy ...

**Comment by bchong95** [comment]
I think that's just yahoo search sucking.

**Comment by bchong95** [comment]
Chrome seems to like us better, but I think we can have a better webpage description:

![image](https://cloud.githubusercontent.com/assets/4381236/21627350/cafb5b56-d1dc-11e6-8249-0ba5bdb59543.png)

**Comment by bhuvy2** [comment]
We made our website more mobile friendly with lightweight bootstrap, moving some more js files to the server and allowing smaller packaging will keep us at the top.
