### ISSUE TITLE
On hover anchor link

### ISSUE THREAD

**Issue by bchong95** [illinois-cs241/illinois-cs241.github.io#43]
I would like for hovering over a section title to reveal an anchor link.

![image](https://cloud.githubusercontent.com/assets/4381236/20640452/d3e1a132-b3a3-11e6-951b-450311c1fb33.png)

Clicking on this should copy the link to your clipboard, so it's easier to cite parts of the docs.

**Comment by bhuvan-venkatesh** [comment]
In order to get formal clipboard copying without doing anything like forking packages, We need to get #16 solved as well.

**Comment by earwig** [comment]
I don't really recommend copying the link to the clipboard automatically, since most sites that I know of don't do this. You can just right-click and copy the link or click on it and copy the address bar.

**Comment by bchong95** [comment]
Hmm okay yeah it's probably overkill to copy into your clipboard.

Were I got the screenshot: 
https://facebook.github.io/react/tutorial/tutorial.html

It just jumps to the anchor and updates the urlbar.

**Comment by bchong95** [comment]
Not sure if jekyll templating will insert the links after all the headers for us, but a minimal amount of css and js will get us the feature.

http://ben.balter.com/2014/03/13/pages-anchor-links/

Can you revert the commit with the library and implement this in a branch, so we can PR?

**Comment by bhuvy2** [comment]
Done with travis integration + building.
