### ISSUE TITLE
spell check 

### ISSUE THREAD

**Issue by bchong95** [illinois-cs241/illinois-cs241.github.io#52]
Can someone run spell check once on all the pages.

I just think it's low hanging fruit that makes the course look a bit more polished.

**Comment by bhuvan-venkatesh** [comment]
Should we start scripting the build hand have a command that runs `spell` or `aspell` on each of the pages/posts?

**Comment by bchong95** [comment]
Yeah maybe a precommit hook would be nice. As long as the tool is smart enough to ignore code blocks, markdown specific syntax, and allows for a dictionary that we can load with CS lingo, then I can see it being super helpful.

**Comment by bhuvan-venkatesh** [comment]
https://www.npmjs.com/package/markdown-spellcheck is probably a better tool. It parses the markdown once and only looks for typos in rendered portions, we can load a dictionary and it is made by CS people so they already have a bunch of our stuff covered (they don't have things like chara though)/

**Comment by bchong95** [comment]
https://github.com/illinois-cs241/illinois-cs241.github.io/commit/3cf0a693f448019bdd77d794bc4d7e593aedd7e1

I think this is just something people should manually run, since code blocks and uiuc terms can't be automated away
