### ISSUE TITLE
Make site async/load friendly

### ISSUE THREAD

**Issue by bhuvy2** [illinois-cs241/illinois-cs241.github.io#54]
So we have a lot of css/js in our head blocking the site from loading. We should introduce requirejs and stagger our dependencies loading so the site takes less time to load, this also helps with #37 because google and other search engines use speed metrics to determine rankings.

* Analytics should definitely not be in head.

We ought to set timeouts/caches as well as minify the files (maybe use grunt to automate that?)

**Comment by bchong95** [comment]
Good call!

**Comment by bhuvan-venkatesh** [comment]
https://developers.google.com/speed/pagespeed/insights/?url=cs241.cs.illinois.edu.

* Eliminate render-blocking JavaScript and CSS in above-the-fold content (head)
* Leverage browser caching (serve our sources from a CDN with a longer Cache-Control)
* Minify CSS

**Comment by bhuvy2** [comment]
With website redesign, this is a non-issue. We will just have to keep it light going forward.
