### ISSUE TITLE
Staff picture placeholder

### ISSUE THREAD

**Issue by bchong95** [illinois-cs241/illinois-cs241.github.io#59]
We should change the templating engine put up placeholder for staff that haven't uploaded a photo yet.

I would highly like this photo: 

![image](https://cloud.githubusercontent.com/assets/4381236/22044483/92838434-dcda-11e6-8072-e3424b2e13e4.png)

**Comment by earwig** [comment]
The staff page uses `images/staffPhotos/default.jpg` if none exists, so that part already works.

Hopefully Nintendo won't come after us for violating copyright if we use that, LOL.
