### ISSUE TITLE
different pokemon everytime

### ISSUE THREAD

**Issue by bchong95** [illinois-cs241/illinois-cs241.github.io#60]
For the default image on the course staff page can we get a different pokemon every time?

This website does it well:

https://gearoid.me/pokemon

Here is a blank template:
![image](https://cloud.githubusercontent.com/assets/4381236/22049196/774a497e-dcf7-11e6-8a6b-39b951b86f7b.png)

**Comment by bchong95** [comment]
I am not being too serious

**Comment by earwig** [comment]
\>_>;

**Comment by bchong95** [comment]
Ok I was just trolling
