### ISSUE TITLE
Labs page needs staff assignments 

### ISSUE THREAD

**Issue by bchong95** [illinois-cs241/illinois-cs241.github.io#63]
It would be nice if we listed who ran each section (on the labs page) so students know who to email. 

Please make sure that this is generated using liquid templating, _data, and has an accompanying mobile friendly table. Make this a PR and I'll review it.

**Comment by redsn0w422** [comment]
This would go under the "lab sections" page, right?

**Comment by bchong95** [comment]
Yep!

**Comment by bhuvan-venkatesh** [comment]
Why don't we just have this on the calendar? It is easier to change.

**Comment by bchong95** [comment]
Hmm I guess that works  :P
