### ISSUE TITLE
Can slides be in their own repo

### ISSUE THREAD

**Issue by bchong95** [illinois-cs241/illinois-cs241.github.io#68]
they have their own workflow and what not

**Comment by bhuvan-venkatesh** [comment]
They are in the handouts repo, everything needed to generate them is there as well. What do you mean own repo?

**Comment by bchong95** [comment]
https://github.com/illinois-cs241/illinois-cs241.github.io/tree/master/lab_resources

has stuff right?

**Comment by bchong95** [comment]
if you are worried that they will render with `text/plain` mine type then we can use:

http://htmlpreview.github.io/

**Comment by bchong95** [comment]
this will handle slides but handouts are a private repo ...
