### ISSUE TITLE
How to read documentation guide

### ISSUE THREAD

**Issue by bchong95** [illinois-cs241/illinois-cs241.github.io#73]
We should have a guide about how reading docs in a computer science course is not the same as reading an api for a large open source project. In the real world learning to skim documentation is a skill that pays off very well, since most of the time you are just trying to call one function. 

Just doesn't fly with a programming code, since you are expected to implement every line of the documentation. Also thought experiment "would the ta bother to write this line of the docs if they thought it wasn't important??"

**Comment by Robert-Andrews** [comment]
I'm not sure how necessary this is. It seems akin to telling the students, "No, really, you need to read the *whole* assignment."

**Comment by earwig** [comment]
Expecting students to read the docs so we can tell them to read the docs? Unlikely to make a difference.
